### ISSUE TITLE
Migrations ordering issue

### ISSUE THREAD

**Issue by dimuska139** [go-gormigrate/gormigrate#33] opened 2019-03-22 15:41 UTC
If you have InitSchema migration and another migrations on the first start, schema initialization migration is applied after other migrations. There are no changes in the database structure, but migrations are recorded in the migrations table. Because of migrations are applied to non-existent database schema.

```go
func Migrate() error {
	connection, err := db.Db.GetConnection(true)
	if err != nil {
		return fmt.Errorf("get database connection: %v", err)
	}

	m := gormigrate.New(connection, migrationsOptions, []*gormigrate.Migration{
		m201901291100,
		m201902041157,
		m201902151152,
		m201903121503,
		m201903130943,
		m201903151255,
	})

	m.InitSchema(func(tx *gorm.DB) error {
		fmt.Println("Init database schema")
		err := tx.AutoMigrate(
			&entities.Notification{},
		).Error
		if err != nil {
			return fmt.Errorf("init schema: %v", err)
		}

		return nil
	})

	if err := m.Migrate(); err != nil {
		return fmt.Errorf("migrate: %v", err)
	}

	return nil
}
```

**Comment by andreynering** [comment] 2019-03-23 20:12
Hi @dimuska139, and thank for opening this issue!

I'm sorry, but I couldn't understand the issue.

I behavior is like this:

1) If a `InitSchema` function is given
2) And if there is no migration on the inserted to the `migrations` table

Then it runs the `InitSchema` function you gave and insert all migration IDs to the table, but without actually running then.

If any of these conditions is false, then it just loops through the migration list running + inserting the ID for then.

**Comment by dimuska139** [comment] 2019-03-25 08:19
@andreynering 

> and insert all migration IDs to the table, but without actually running then

What is the purpose of recording the migration IDS to the table applied, if in fact they are not applied? If I understand you correctly.

The problem is that if the database is empty (completely) and there are any migrations, the migrations are written to the table, but in fact they are not applyed. Because of it tryes to apply migrations (to add foreigh key for example, or change column name) before it runs InitSchema. I suppose that InitSchema should create database structure before apply migrations m201901291100, m201902041157 etc.

**Comment by andreynering** [comment] 2019-03-25 10:33
> I suppose that InitSchema should create database structure before apply migrations m201901291100, m201902041157 etc.

No. InitSchema is supposed to your entire schema, and it's by design it skip all migrations after running that.

You have to ensure this function is up-to-date with migrations, and create *everything* your app needs.

**Comment by andreynering** [comment] 2019-03-25 10:39
I think it'd make sense to have an option to inform which migration ID InitSchema is up-to-date with.

For example, if `201903121503`, then it'd run all migrations declared after that.

**Comment by dimuska139** [comment] 2019-03-25 10:50
@andreynering 
```
package entities
import "github.com/jinzhu/gorm"

type Group struct {
    Id   uint   `gorm:"primary_key"`
    Name string `gorm:"not null;column:name;type:varchar(100)"`
    Slug string `gorm:"not null;column:slug;type:varchar(200)"`
}

type Project struct {
    Id   uint   `gorm:"primary_key"`
    Name    string `gorm:"not null;column:name;type:varchar(100)"`
    Slug    string `gorm:"not null;column:slug;type:varchar(200)"`
    Group   Group
}
```
I agree, everything looks logical. But InitSchema in this case creates two tables (for groups and projects), but "Projects" table doesn't contain "group_id" field with foreign key on it. I don't understand: is it Gorm bug or not (http://doc.gorm.io/associations.html#belongs-to). So i tried to add field group_id and fk manually in separate migration to solve this problem. I can not add this logic to struct "Project" to create field group_id with fk in automigration that should be applyed in InitSchema.

```
package migrations

import (
	"github.com/jinzhu/gorm"
	"gopkg.in/gormigrate.v1"
)

var m201901291100 = &gormigrate.Migration{
	ID: "201901291100",
	Migrate: func(db *gorm.DB) error {
		return db.Exec("ALTER TABLE projects ADD CONSTRAINT projects_group_id_fk_groups_id FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE SET NULL").Error
	},
}
```

**Comment by andreynering** [comment] 2019-03-25 22:55
@dimuska139 Gorm doesn't automatically add a `group_id` column just because you added `Group` association. You should also add `GroupId int` field to make it work.

Also, it doesn't automatically add foreign key constraints for you. See: http://doc.gorm.io/database.html#migration

**Comment by dimuska139** [comment] 2019-03-26 08:28
@andreynering "Also, it doesn't automatically add foreign key constraints for you" - so I should add it in migration (not in InitSchema), right? If it so, I should call InitSchema and custom migration (that creates fk). If another programmer clones my repository and tryes to start project at his host (with empty database without schema), what will be the order of migrations applying? "InitSchema" (1) and "custom migration that creates fk on existing table" (2) after that or "custom migration that creates fk on existing table" (1) and "InitSchema" (2) after that?

**Comment by dimuska139** [comment] 2019-03-26 08:36
```
func Migrate() error {
	connection, err := db.Db.GetConnection(true)
	if err != nil {
		return fmt.Errorf("get database connection: %v", err)
	}

	m := gormigrate.New(connection, migrationsOptions, []*gormigrate.Migration{
		migrationToCreateFkManually,
	})

	m.InitSchema(func(tx *gorm.DB) error {
		fmt.Println("Init database schema")
		err := tx.AutoMigrate(
			&entities.Project{},
                        &entities.Group{},
		).Error
		if err != nil {
			return fmt.Errorf("init schema: %v", err)
		}

		return nil
	})

	if err := m.Migrate(); err != nil {
		return fmt.Errorf("migrate: %v", err)
	}

	return nil
}
```

**Comment by andreynering** [comment] 2019-03-26 10:47
@dimuska139 Only `InitSchema` will run for clean databases, so you should also create your foreign keys there.

I'll close this issue since we're walking in circles here.

If you need more general help, you can ask on StackOverflow, the [Go Forum](https://forum.golangbridge.org/), the [Go Subreddit](https://www.reddit.com/r/golang/), the [Go Slack](https://invite.slack.golangbridge.org/) or other public spaces for that.

**Closed by andreynering** 2019-03-26 10:47 UTC
Labels: question
