### ISSUE TITLE
Gormigrate doesn't allow specifying a schema on the TableName option

### ISSUE THREAD

**Issue by RevProg** [go-gormigrate/gormigrate#30] opened 2019-02-28 17:06 UTC
Hi,
First of all thank you for gomigrate. It`s very usefull.
I have a problems with postgres database with several schemas.
In case if we got sql with additional shemas in migration, gorm HasTable method returns false, even if table really exists, so createMigrationTableIfNotExists trying to create table and fails(even if I add schema to migration table name in options). I know this is gorm issue, but after checking their repo issues I found that this known problem and will not to be fixed soon.

What about custom method to check table existing?

Thank you

**Comment by andreynering** [comment] 2019-03-03 17:00
Hi @RevProg,

Ideally, this should be fixed on Gorm itself instead of here. I'd encourage you to open another issue there with details and a reproduction script (it doesn't need to include Gormigrate, just a failing `HasTable` call).

**Comment by avakarev** [comment] 2023-06-02 00:16
@hi @RevProg, unfortunately `gormigrate` has nothing to do with gorm dialect-specific databases because it operates on top of `gorm` and the dialect implementing [Migrator Interface](https://gorm.io/docs/migration.html#Migrator-Interface).
Please, contact the team behind [postgres dialect](https://github.com/go-gorm/postgres) regarding schema support.
Sorry for no help.

Closing this issue as irrelevant.

**Closed by avakarev** 2023-06-02 00:16 UTC
Labels: bug
